name: unlockr
base: core22 
adopt-info: unlockr
grade: stable
confinement: strict
license: GPL-3.0-only
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  qpdf:
    source: https://github.com/qpdf/qpdf.git
    source-tag: "v11.4.0"
    source-depth: 1
# ext:updatesnap
#   version-format:
#     ignore: true
    build-packages:
      - libjpeg-turbo8-dev
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DINSTALL_PKGCONFIG=ON
      - -DINSTALL_CMAKE_PACKAGE=OFF
      - -DINSTALL_EXAMPLES=OFF
    prime:
      - -usr/lib/*/pkgconfig
  unlockr:
    after: [ qpdf ]
    plugin: meson
    source: https://github.com/jkotra/unlockr.git
    source-tag: '0.9.1'
    source-depth: 1
    parse-info: [ usr/share/metainfo/com.github.jkotra.unlockr.metainfo.xml ]
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
    meson-parameters:
      - --prefix=/snap/unlockr/current/usr
    organize:
      snap/unlockr/current: .

slots:
  unlockr:
    interface: dbus
    bus: session
    name: com.github.jkotra.unlockr

apps:
  unlockr:
    command: usr/bin/unlockr
    extensions: [ gnome ]
    common-id: com.github.jkotra.unlockr
    desktop: usr/share/applications/com.github.jkotra.unlockr.desktop
    plugs:
      - home
